language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- stable
os:
- linux
script:
- npm run lint
after_success:
- npm run semantic-release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
