language: node_js
env:
  global:
  - secure: e18qiWk0rAi9D58VPu7Gm1tlaHyi1CxTwXf4BxcnL6qkAm2/XF8HkVZL0Hu7btWPZX5PKmH63I22PN1vtUa0HrWn91dR9F58QjtOKh2U+pQm9t84Px9cV2ftw+bPV+hEYhUC0wBqNFkHcMVIYDbNpff606kcbO/RDC5lQ0lUSg/gDwazMBGFtaNlBm33AmbW0YXRM0dWMKEUL5H6iIOIcvMZ8B1kUihYA9PnX0rR1Z9NIozyHOjgZeCMnkypesI8D74wjPqi6TLb6SvLmJMdStqWBdyTnQw3YB7nAJWlmWNw/RWfmfZybJb98B08ZJvGhCGrcm3awriZRC7OOMqcxNyODijV0btcEYtL0qAZ7RgxMrpB8u8dvZwCWK8OGXTzr2FILp5NDkFZuRUW5uFKzWQhBQKjAUxiuJ+qYusGJ3cnP/AbiBB6JxfW2D4fPSlzq6owH5sL8biXk9H6gQtgA5q7VfTIXt0wro+FnJyvH03M4/uVBXN0B8+iAhn8guaUTrsTza+/D02ZR776Cvg9rf9rwnOAgr+l3ClQ9TZUxcfoumwHgduu7CbacXN6pIgrnPSLGOVuMLIZEHbH+xC0sWxfvnolGk7ICVONuxnmWe145WX6Qah0I+fYlp3U1mZzDpAehZRU76EUNSFCPc0U5Sfz15x8eXh4QSqrtale5Js=
  - secure: dbnSw6428sO9NHz8TUoa88szKE9Do7wx0OBijIG5/c4K3zcgraPmwgZTcx/O7iQZyavGoeg5Bfe41bfLChIhMofaDMbenAQQnYztVtdiw6u5NmIH3tX0tv//sivcIqdCXXWCbA8xT6Ysq8OIckM36egKglRY3XRaL/bevQgD6LGTdt0KBym8B24SqS5SBrpQ5z3gy1Pw1UaFFUrUxE8fCZsYCOhtVZOshN/rMDCQW1QzewVSSBZ3S9qB7c15UK2XDc7lB48TYZckc8GJpTbldElgWLxeFQ6DWRor05SNATi66qjzE62vXB0rct7MsTOQZg2yCYSoewvKmND/VWP8yihg2QOXQs3uQeZXYUWg7ykwnVHTweq6f6bty9LuOjddlnA9zqtdUpChDyeOzgtMrSsEXYxczttrrEgd6jPdSJCL7Ndd4HuMLvGNP1RwZbN2iuXY9n5+XyQsyL8S7dJZlaBiayQfUnC5S1+m39eNmesxlluyw4rNIDpMsYe1D7BtwIL26XWUvx6xnVbnTd/LjSEcR3kGXNdSOjoOhoz6T20pVuJ/tjv432d/13tGIN4QSe0SPRbeCY6srFKqxqvlvgQH6lrDg/P6meuNa1kIL3Kq9HZXhHwLsISPKnZEZmkpJeqqI/ev21f8sKQnlNNl8w7MPs2lBv7PnOI6YDo1gQ8=
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- stable
os:
- linux
script:
- npm run lint
after_success:
- npm run semantic-release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
